CREATE TABLE t_user_0306 (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     name VARCHAR(100) NOT NULL,
     age INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE t_download_task_0306 (
      id BIGINT PRIMARY KEY AUTO_INCREMENT,
      file_name VARCHAR(255) NOT NULL,
      status TINYINT NOT NULL COMMENT '0-待处理 1-处理中 2-成功 3-失败',
      fail_reason VARCHAR(500),
      last_id BIGINT DEFAULT 0 COMMENT '断点续传记录的最后一条ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE t_download_task_detail_0306 (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     task_id BIGINT NOT NULL,
     sql_text TEXT NOT NULL,
     column_model TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO t_user_0306 (name, age)
SELECT
    CONCAT('user_', @rownum := @rownum + 1),
    FLOOR(19 + RAND() * 40)
FROM
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d,
    (SELECT @rownum := 0) r
LIMIT 6000;

INSERT INTO t_user_0306 (name, age)
SELECT
    CONCAT('user_', @rownum2 := @rownum2 + 6000),
    FLOOR(1 + RAND() * 18)
FROM
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
    (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d,
    (SELECT @rownum2 := 0) r
LIMIT 4000;


SELECT COUNT(*) FROM t_user_0306;

SELECT COUNT(*) FROM t_user_0306 WHERE age > 18;

SELECT COUNT(*) FROM t_user_0306 WHERE age <= 18;